export const database = [
  {
    product: 'ventilador ciclón 18" universal',
    disponibilidad: true,
    descuento: false,
    id: "001",
    price: "491,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/L75920---VENTILADOR-INDUSTRIAL-CICLON.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador fresh ultra 3 en 1 18" universal',
    disponibilidad: true,
    descuento: false,
    id: "002",
    price: "399,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/119695878_1.jpeg",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador fresh ultra 3 en 1 18" universal',
    disponibilidad: true,
    descuento: false,
    id: "003",
    price: "359,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/6f91be304897dfdef36fed4568858cb3-product.jpeg",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador silence force plus 18" blanco samurai',
    disponibilidad: true,
    descuento: false,
    id: "004",
    price: "289,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/5861030024-1.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: "ventilador fresh de pared universal",
    disponibilidad: true,
    descuento: false,
    id: "005",
    price: "283,900",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/164927-1200-auto.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador 3 en 1 18" blanco kalley',
    disponibilidad: true,
    descuento: false,
    id: "006",
    price: "270,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/157282-1200-auto.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador silence force 18" samurai',
    disponibilidad: true,
    descuento: false,
    id: "007",
    price: "252,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/158282-800-auto.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador ultra power 18" universal',
    disponibilidad: true,
    descuento: false,
    id: "008",
    price: "249,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/D_NQ_NP_683567-MCO32904979542_112019-O.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador 2 en 1 16" negro corona',
    disponibilidad: true,
    descuento: false,
    id: "009",
    price: "210,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/D_NQ_NP_684183-MCO48896089889_012022-O.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador de piso y pared 8" universal',
    disponibilidad: true,
    descuento: false,
    id: "010",
    price: "129,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/159345-1200-auto.png",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: "mini ventilador de mesa y pinza  110v giratorio",
    disponibilidad: true,
    descuento: false,
    id: "011",
    price: "80,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/D_NQ_NP_881680-MCO50529069335_062022-O.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: "ventilador portatil plegable con lampara 20cmx33cm",
    disponibilidad: true,
    descuento: false,
    id: "012",
    price: "75,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector-1.jpeg",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
];
