export const database = [
  {
    product: 'ventilador ciclón 18" universal',
    disponibilidad: true,
    descuento: false,
    id: "001",
    price: "491,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/L75920---VENTILADOR-INDUSTRIAL-CICLON.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador fresh ultra 3 en 1 18" universal',
    disponibilidad: true,
    descuento: false,
    id: "002",
    price: "399,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/119695878_1.jpeg",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador fresh ultra 3 en 1 18" universal',
    disponibilidad: true,
    descuento: false,
    id: "003",
    price: "359,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/6f91be304897dfdef36fed4568858cb3-product.jpeg",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador silence force plus 18" blanco samurai',
    disponibilidad: true,
    descuento: false,
    id: "004",
    price: "289,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/5861030024-1.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: "ventilador fresh de pared universal",
    disponibilidad: true,
    descuento: false,
    id: "005",
    price: "283,900",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/164927-1200-auto.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador 3 en 1 18" blanco kalley',
    disponibilidad: true,
    descuento: false,
    id: "006",
    price: "270,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/157282-1200-auto.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador silence force 18" samurai',
    disponibilidad: true,
    descuento: false,
    id: "007",
    price: "252,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/158282-800-auto.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador ultra power 18" universal',
    disponibilidad: true,
    descuento: false,
    id: "008",
    price: "249,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/D_NQ_NP_683567-MCO32904979542_112019-O.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador 2 en 1 16" negro corona',
    disponibilidad: true,
    descuento: false,
    id: "009",
    price: "210,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/D_NQ_NP_684183-MCO48896089889_012022-O.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador de piso y pared 8" universal',
    disponibilidad: true,
    descuento: false,
    id: "010",
    price: "129,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/159345-1200-auto.png",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: "mini ventilador de mesa y pinza  110v giratorio",
    disponibilidad: true,
    descuento: false,
    id: "011",
    price: "80,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/D_NQ_NP_881680-MCO50529069335_062022-O.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: "ventilador portatil plegable con lampara 20cmx33cm",
    disponibilidad: true,
    descuento: false,
    id: "012",
    price: "75,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector-1.jpeg",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'soporte para tv de 40" a 80',
    disponibilidad: true,
    descuento: false,
    id: "013",
    price: "173,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/D_NQ_NP_641713-MCO70610746472_072023-O.webp",
    category: "electrodomesticos",
    sub_category: "televisores",
  },
  {
    product: 'soporte para tv de 14" a 55',
    disponibilidad: true,
    descuento: false,
    id: "014",
    price: "50,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/gsc_126422648_4549529_1.jpeg",
    category: "electrodomesticos",
    sub_category: "televisores",
  },
  {
    product: 'soporte para tv de 14" a 42',
    disponibilidad: true,
    descuento: false,
    id: "015",
    price: "28,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/D_NQ_NP_976169-MLA48232092452_112021-O.webp",
    category: "electrodomesticos",
    sub_category: "televisores",
  },
  {
    product: "cable hdtv 3m",
    disponibilidad: true,
    descuento: false,
    id: "016",
    price: "12,900",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/13/Cable-Hdmi.jpeg",
    category: "electrodomesticos",
    sub_category: "televisores",
  },
  {
    product: "sanduchera 3 en 1 4 puestos universal",
    disponibilidad: true,
    descuento: false,
    id: "017",
    price: "256,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/f3510f82389bf15ad950eb6596039a78-product.jpeg",
    category: "electrodomesticos",
    sub_category: "sanducheras y wafleras",
  },
  {
    product: "sanduchera panini grill universal",
    disponibilidad: true,
    descuento: false,
    id: "018",
    price: "239,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/panini-grill-universal-l87312-negro.webp",
    category: "electrodomesticos",
    sub_category: "sanducheras y wafleras",
  },
  {
    product: "sanduchera 3 en 1 2 puestos universal",
    disponibilidad: true,
    descuento: false,
    id: "019",
    price: "189,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/Sanduchera-UNIVERSAL-Multifuncional---3en1.webp",
    category: "electrodomesticos",
    sub_category: "sanducheras y wafleras",
  },
  {
    product: "sanduchera panini kalley",
    disponibilidad: true,
    descuento: false,
    id: "020",
    price: "119,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/D_NQ_NP_739000-MCO42720126903_072020-O.webp",
    category: "electrodomesticos",
    sub_category: "sanducheras y wafleras",
  },
  {
    product: "sanduchera mini panini universal",
    disponibilidad: true,
    descuento: false,
    id: "021",
    price: "136,200",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/13/162187-1200-auto.webp",
    category: "electrodomesticos",
    sub_category: "sanducheras y wafleras",
  },
  {
    product: "maquina cortadora evok",
    disponibilidad: true,
    descuento: false,
    id: "022",
    price: "168,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/0072216_029e936f3f0064d7375bf20d367b113d9c7bfebf6180d83f02058f58d3ca82ed_450.png",
    category: "salud",
    sub_category: "",
  },
  {
    product: "cojín coxis ortopédico para silla 42cm x 38cm x 12cm",
    disponibilidad: true,
    descuento: false,
    id: "023",
    price: "125,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/13/1092_4.webp",
    category: "salud",
    sub_category: "",
  },
  {
    product: "tensiómetro digital jziki",
    disponibilidad: true,
    descuento: false,
    id: "024",
    price: "98,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/D_NQ_NP_814508-MLA54904597227_042023-O.webp",
    category: "salud",
    sub_category: "",
  },
  {
    product: "bascula inteligente peso corporal recargable 25cm x 26cm",
    disponibilidad: true,
    descuento: false,
    id: "025",
    price: "69,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/D_Q_NP_957322-MLA54249617532_032023-O.webp",
    category: "salud",
    sub_category: "",
  },
  {
    product: "dispensador crema dental soporte esterilizador",
    disponibilidad: true,
    descuento: false,
    id: "026",
    price: "46,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/soporte-esterilizador-uv-cepillo-de-dientes-dispensador-crema-dental.webp",
    category: "salud",
    sub_category: "",
  },
  {
    product: "rueda de ejercicios abdominales con tapete",
    disponibilidad: true,
    descuento: false,
    id: "027",
    price: "45,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/Kit-de-rodillos-de-rueda-Abdominal-5-en-1-con-barra-de-realce-cuerda-de-saltar.jpg_.webp",
    category: "salud",
    sub_category: "",
  },
  {
    product: "bascula personal max 150kg",
    disponibilidad: true,
    descuento: false,
    id: "028",
    price: "43,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/bascula-balanza-pesa-personal-bano-vidrio-digital-180k-D_NQ_NP_696087-MCO43675982688_102020-F.jpeg",
    category: "salud",
    sub_category: "",
  },
  {
    product: "set x2 pesas de 2 kilos",
    disponibilidad: true,
    descuento: false,
    id: "029",
    price: "35,500",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/61hBPTY5gYL._AC_SY450_.jpeg",
    category: "salud",
    sub_category: "",
  },
  {
    product: "faja cinturilla reductora neopropeno",
    disponibilidad: true,
    descuento: false,
    id: "030",
    price: "27,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/imageff2192125f8b0cbf.png",
    category: "salud",
    sub_category: "",
  },
  {
    product: "pesa 1kg fisioterapia",
    disponibilidad: true,
    descuento: false,
    id: "031",
    price: "25,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/pesas-fit-dama-hombre-ejercicio-fisioterapia-1-kilo-x1-unidad-kidshoptiendavirtual-1169855311.webp",
    category: "salud",
    sub_category: "",
  },
  {
    product: "taloneras ortopedicas ultra descanso",
    disponibilidad: true,
    descuento: false,
    id: "032",
    price: "21,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/gsc_119215925_2261901_3.jpeg",
    category: "salud",
    sub_category: "",
  },
  {
    product: "corrector de postura lumbar espaldar silla",
    disponibilidad: true,
    descuento: false,
    id: "033",
    price: "20,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/D_NQ_NP_946161-MCO49697721608_042022-O.webp",
    category: "salud",
    sub_category: "",
  },
  {
    product: "pesa fit boy toys 1kg colores varios",
    disponibilidad: true,
    descuento: false,
    id: "034",
    price: "19,900",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/gsc_117936392_1915716_1.jpeg",
    category: "salud",
    sub_category: "",
  },
  {
    product: "mancuerna rusa 2.5kg boy toys",
    disponibilidad: true,
    descuento: false,
    id: "035",
    price: "19,600",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/13/image2.png",
    category: "salud",
    sub_category: "",
  },
  {
    product: "set guante protector de muñeca y tobillo en tela",
    disponibilidad: true,
    descuento: false,
    id: "036",
    price: "15,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/ultunidades-bandas-ortopedicas-modelos-varios.jpeg",
    category: "salud",
    sub_category: "",
  },
  {
    product: "bolsa térmica para agua fría o caliente motivos varios",
    disponibilidad: true,
    descuento: false,
    id: "037",
    price: "14,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/61FunA4l95L._AC_SX425_.jpeg",
    category: "salud",
    sub_category: "",
  },
  {
    product: "plancha a vapor universal",
    disponibilidad: true,
    descuento: false,
    id: "038",
    price: "140,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/156069-1200-auto.webp",
    category: "electrodomesticos",
    sub_category: "plancha",
  },
  {
    product: "plancha seca universal",
    disponibilidad: true,
    descuento: false,
    id: "039",
    price: "99,900",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/160774-1200-auto.webp",
    category: "electrodomesticos",
    sub_category: "plancha",
  },
  {
    product: "plancha a vapor extra liviana universal",
    disponibilidad: true,
    descuento: false,
    id: "040",
    price: "89,900",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/image-87ec96dbbcc242248cdecbd38a6e3e45.webp",
    category: "electrodomesticos",
    sub_category: "plancha",
  },
  {
    product: "exprimidor de citricos cusinart",
    disponibilidad: true,
    descuento: false,
    id: "041",
    price: "299,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/88895-1_1000x.webp",
    category: "electrodomesticos",
    sub_category: "",
  },
  {
    product: "procesador manual 3 en 1 universal",
    disponibilidad: true,
    descuento: false,
    id: "042",
    price: "220,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/L89125electro1.jpeg",
    category: "electrodomesticos",
    sub_category: "",
  },
  {
    product: "batidora multiuso black & decker",
    disponibilidad: true,
    descuento: false,
    id: "043",
    price: "204,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/531159-800-800.webp",
    category: "electrodomesticos",
    sub_category: "",
  },
  {
    product: "procesador de alimentos universal",
    disponibilidad: true,
    descuento: false,
    id: "044",
    price: "180,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/157724-1200-auto.png",
    category: "electrodomesticos",
    sub_category: "",
  },
  {
    product: "horno tostador kalley",
    disponibilidad: true,
    descuento: false,
    id: "045",
    price: "159,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/160023-1200-auto.webp",
    category: "electrodomesticos",
    sub_category: "",
  },
  {
    product: "picatodo chopper mix univesal 375ml",
    disponibilidad: true,
    descuento: false,
    id: "046",
    price: "109,900",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/173415-1200-auto.webp",
    category: "electrodomesticos",
    sub_category: "",
  },
  {
    product: "exprimir blanco kalley",
    disponibilidad: true,
    descuento: false,
    id: "047",
    price: "109,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/16232-1-eletrodomesticos-exprimidor-electrico-blanco-kalley.webp",
    category: "electrodomesticos",
    sub_category: "",
  },
  {
    product: "tostador de pan kalley",
    disponibilidad: true,
    descuento: false,
    id: "048",
    price: "104,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/7705946492249-001-750Wx750H.png",
    category: "electrodomesticos",
    sub_category: "",
  },
  {
    product: "batido de mano universal",
    disponibilidad: true,
    descuento: false,
    id: "049",
    price: "94,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/160055-1200-auto.webp",
    category: "electrodomesticos",
    sub_category: "",
  },
  {
    product: "wok opalo 24cm + tapa de vidrio",
    disponibilidad: true,
    descuento: false,
    id: "050",
    price: "66,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/D_NQ_NP_804003-MCO48001919296_102021-O-1.webp",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "sartén talent master deluxe antiadherente 26cm+ tapa de vidrio",
    disponibilidad: true,
    descuento: false,
    id: "051",
    price: "87,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/7702073038111-1.webp",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "olla aliada antiadherente 24cm + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: "052",
    price: "69,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/image-1.png",
    category: "cocina",
    sub_category: "ollas",
  },
  {
    product: "sartén artik 24cm universal",
    disponibilidad: true,
    descuento: false,
    id: "053",
    price: "62,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/224388-1200-1200.webp",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "olla talent triforce 18cm + tapa de vidrio imusa",
    disponibilidad: true,
    descuento: false,
    id: "054",
    price: "61,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/162465-800-auto.webp",
    category: "cocina",
    sub_category: "ollas",
  },
  {
    product: "sartén talent master deluxe antiadherente 18cm + tapa de vidrio",
    disponibilidad: true,
    descuento: false,
    id: "055",
    price: "57,800",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/5861032067-2.webp",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "portacomida lunch box acero inoxidable 1.5 lt incluye cuchara",
    disponibilidad: true,
    descuento: false,
    id: "056",
    price: "55,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector-1.jpeg",
    category: "cocina",
    sub_category: "",
  },
  {
    product: "plancha asadora 6 ultra 23cm universal",
    disponibilidad: true,
    descuento: false,
    id: "057",
    price: "53,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/179590-800-auto.png",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "sartén opalo 20cm antiadherente + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: "058",
    price: "46,000",
    description: "",
    images_url: "https://tinypic.host/image/wTjWh",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "olla 6 ultra 24cm universal",
    disponibilidad: true,
    descuento: false,
    id: "059",
    price: "79,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/L72408ollacocina1.jpeg",
    category: "cocina",
    sub_category: "ollas",
  },
  {
    product: "wok 6 ultra 24cm + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: "060",
    price: "75,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/159343-1200-auto.png",
    category: "cocina",
    sub_category: "ollas",
  },
  {
    product: "wok 6 ultra 24cm universal",
    disponibilidad: true,
    descuento: false,
    id: "061",
    price: "53,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/images-removebg-preview.png",
    category: "cocina",
    sub_category: "ollas",
  },
  {
    product: "cacerola aliada asa 16cm + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: "062",
    price: "42,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/Cacerola-Universal-16Cm-T-Vidr-L38712.webp",
    category: "cocina",
    sub_category: "ollas",
  },
  {
    product: "bateria 6 ultra 12 piezas universal",
    disponibilidad: true,
    descuento: false,
    id: "063",
    price: "329,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/D_NQ_NP_807651-MCO42867453234_072020-O.webp",
    category: "cocina",
    sub_category: "baterias de cocina",
  },
  {
    product: "bateria de cocina trend 7 piezas antiadherente everhouse",
    disponibilidad: true,
    descuento: false,
    id: "064",
    price: "276,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/bateria-ollas-7-piezas-ever-house-44535-set-antiadherente.webp",
    category: "cocina",
    sub_category: "baterias de cocina",
  },
  {
    product: "bateria de cocina 11 piezas universal",
    disponibilidad: true,
    descuento: false,
    id: "065",
    price: "255,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/D_NQ_NP_803606-MCO43364661797_092020-O.webp",
    category: "cocina",
    sub_category: "baterias de cocina",
  },
  {
    product: "bateria aliada 8 piezas universal",
    disponibilidad: true,
    descuento: false,
    id: "066",
    price: "178,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/image-319c4805adce4e5790b5110dc9a47ab2.webp",
    category: "cocina",
    sub_category: "baterias de cocina",
  },
  {
    product: "caldero fundido + tapa fundida 9,5lb 42cm universal",
    disponibilidad: true,
    descuento: false,
    id: "067",
    price: "178,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/l79030_universal.jpeg",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "bateria 7 piezas antiadherente universal",
    disponibilidad: true,
    descuento: false,
    id: "068",
    price: "159,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/160164-1200-auto.webp",
    category: "cocina",
    sub_category: "baterias de cocina",
  },
  {
    product: "bateria de ollas 10 piezas universal",
    disponibilidad: true,
    descuento: false,
    id: "069",
    price: "144,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/D_NQ_NP_691576-MCO46274273221_062021-O.webp",
    category: "cocina",
    sub_category: "baterias de cocina",
  },
  {
    product: "caldero #9 fundido 30 cm incluye tapa de vidrio imusa",
    disponibilidad: true,
    descuento: false,
    id: "070",
    price: "131,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/164053-800-auto.webp",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "plancha grill botanical antiadherente 45x26cm",
    disponibilidad: true,
    descuento: false,
    id: "071",
    price: "120,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/PLANCHA-GRILL-BOTANICAL-45X26-ANTIA..png",
    category: "cocina",
    sub_category: "",
  },
  {
    product: "caldero #5 fundido 24cm 3.5l + tapa de vidrio imusa",
    disponibilidad: true,
    descuento: false,
    id: "072",
    price: "118,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/D_NQ_NP_789088-MLU73409250389_122023-O.webp",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "caldero antiadherente 26cm + tapa de vidrio imusa",
    disponibilidad: true,
    descuento: false,
    id: "073",
    price: "115,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/d6bbfe4186276ae340946ca7c11174b9-product.jpeg",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "olla institucional 9 lts universal",
    disponibilidad: true,
    descuento: false,
    id: "074",
    price: "113,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/L49413_universal.jpeg",
    category: "cocina",
    sub_category: "ollas",
  },
  {
    product: "sarten talent master deluxe 30cm antiadherente + tapa de vidrio",
    disponibilidad: true,
    descuento: false,
    id: "075",
    price: "109,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/D_NQ_NP_915546-MLU72381591475_102023-O.webp",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product:
      "caldero en aluminio fundido antiadherente 22cm + tapa de vidrio imusa",
    disponibilidad: true,
    descuento: false,
    id: "076",
    price: "109,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/image-2.png",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "bateria aliada 4 piezas universal",
    disponibilidad: true,
    descuento: false,
    id: "077",
    price: "99,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/image-3.png",
    category: "cocina",
    sub_category: "baterias de cocina",
  },
  {
    product:
      "caldero en aluminio fundido antiadherente 20cm + tapa de vidrio imusa",
    disponibilidad: true,
    descuento: false,
    id: "078",
    price: "99,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/156344-1200-auto.webp",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "teppamgrill plus elite 34x25cm antiadherente universal",
    disponibilidad: true,
    descuento: false,
    id: "079",
    price: "94,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/295831941_5295016973867157_6580319915232745487_n.png",
    category: "cocina",
    sub_category: "",
  },
  {
    product: "olla talent 24cm triforce + tapa de vidrio imusa",
    disponibilidad: true,
    descuento: false,
    id: "080",
    price: "90,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/162475-1200-auto.png",
    category: "cocina",
    sub_category: "ollas",
  },
  {
    product: "plancha para asar talent antiadherente 27x27cm imusa",
    disponibilidad: true,
    descuento: false,
    id: "081",
    price: "89,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/164191-800-auto.webp",
    category: "cocina",
    sub_category: "",
  },
  {
    product: "caldero en aluminio fundido antiadherente 18cm + tapa de vidrio",
    disponibilidad: true,
    descuento: false,
    id: "082",
    price: "89,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/8186240e35f1751e4985a996105cabcc-product.jpeg",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "sartén wok antiadherente 30cm universal",
    disponibilidad: true,
    descuento: false,
    id: "083",
    price: "89,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/Wok_Universal.jpeg",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "caldero antiadherente experta 30cm universal + tapa de vidrio",
    disponibilidad: true,
    descuento: false,
    id: "084",
    price: "89,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/Caldero-Ant-ExpertaTv-20cm_01.jpeg",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "sartén talent master deluxe 26cm antiadherente + tapa de vidrio",
    disponibilidad: true,
    descuento: false,
    id: "085",
    price: "87,100",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/D_NQ_NP_2X_733899-MLU72112379195_102023-V.webp",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "caldero fundido 30cm + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: "086",
    price: "85,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/image-4.png",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "caldero fundido 30cm 4 Libras + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: "087",
    price: "85,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/156315-800-auto.webp",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "sartén artik 28cm universal",
    disponibilidad: true,
    descuento: false,
    id: "088",
    price: "84,500",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/Sarten-Artik-Tv-20cm-UNIVERSAL-L37306-3027049_a.webp",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "sartén opalo 30cm antiadherente + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: "089",
    price: "84,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/L37223-2.png",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "olla artik 24cm + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: "090",
    price: "79,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/image-eeef2eb747764b13ac36a9d957e2b96e.webp",
    category: "cocina",
    sub_category: "ollas",
  },
  {
    product: "caldero artik 24cm antiadherente + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: "091",
    price: "79,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/Imagen-de-referencia-10.png",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "caldero fundido 26cm 2.5 Libras + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: "092",
    price: "76,200",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/Caldero-Universal-26Cm-T-V-Pomo-Neg-8.webp",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "caldero fundido 26cm 2.5 Libras + tapa fundida universal",
    disponibilidad: true,
    descuento: false,
    id: "093",
    price: "78,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/22-1.jpeg",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "olla aliada 24cm + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: "094",
    price: "75,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/D_NQ_NP_634108-MLA50247712795_062022-O.webp",
    category: "cocina",
    sub_category: "ollas",
  },
  {
    product: "sartén talent master deluxe antiadherente 24cm imusa",
    disponibilidad: true,
    descuento: false,
    id: "095",
    price: "74,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/D_NQ_NP_915546-MLU72381591475_102023-Oaf904833921a3242.webp",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "set de sartenes 18cm 20cm 24cm imusa",
    disponibilidad: true,
    descuento: false,
    id: "096",
    price: "71,600",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/image-56adeb8d8da7ff231.png",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "olla 6 ultra 20cm + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: "097",
    price: "69,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/image-f15ec5b8947743999d5285c58145944f.webp",
    category: "cocina",
    sub_category: "ollas",
  },
  {
    product: "caldero 24cm 3.5L antiadherente universal",
    disponibilidad: true,
    descuento: false,
    id: "098",
    price: "69,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/158323-1200-auto1ebce27dfd4d4e04.png",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "caldero fundido antiadherente 24cm + tapa de pomo verde",
    disponibilidad: true,
    descuento: false,
    id: "099",
    price: "68,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/22-10128a20582fd2188.jpeg",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product:
      "caldero cuadrado 24cm en aluminio fundido + tapa de aluminio universal",
    disponibilidad: true,
    descuento: false,
    id: 100,
    price: "68,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/158049-1200-autod7347435eec9f9f6.webp",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "sartén opalo 30cm antiadherente italiano universal",
    disponibilidad: true,
    descuento: false,
    id: 101,
    price: "66,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/image-1e12d999d7494f54bf45c0b2725c16d8-1ff4c3afe9e4751d4.png",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "caldero artik 20cm antiadherente + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: 102,
    price: "65,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/162203-800-auto0f0befae09d03780.webp",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "sartén talent master deluxe 20cm antiadherente + tapa de vidrio",
    disponibilidad: true,
    descuento: false,
    id: 103,
    price: "64,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/5861032067-2-1.webp",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "wok aliada 24cm antiadherente + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: 104,
    price: "64,200",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/D_NQ_NP_800593-MCO52685721186_122022-O.webp",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "sartén artik 7 ultra antiadherente universal",
    disponibilidad: true,
    descuento: false,
    id: 105,
    price: "62,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/167018-1200-auto189132b8bbf2b7fb.png",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "olla talent 20cm + tapa de vidrio imusa",
    disponibilidad: true,
    descuento: false,
    id: 106,
    price: "60,500",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/162475-1200-auto9adb720ddc65c387.png",
    category: "cocina",
    sub_category: "ollas",
  },
  {
    product: "set x3 sartenes azul 18cm 20cm 24cm universal",
    disponibilidad: true,
    descuento: false,
    id: 107,
    price: "60,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/L39676-SET-X3-COLORS-AZUL-18-20-24---0177c9866c4ef35c9b.webp",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "juego x3 de sartenes 18cm 20cm 24cm universal",
    disponibilidad: true,
    descuento: false,
    id: 108,
    price: "60,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/image-6c8fd55a0a67c7131.png",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "caldero fundido 22cm + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: 109,
    price: "60,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/Captura-8-2a496a75a4d669974.jpeg",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "sartén 6 ultra 24cm antiadherente universal",
    disponibilidad: true,
    descuento: false,
    id: 110,
    price: "60,000",
    description: "",
    images_url:
      "https://almacencoogranada.com/wp-content/uploads/2020/06/L72416sarten1.jpg",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "olla artik 20cm + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: 111,
    price: "59,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/Olla-Universal-Artik-20-cm-con-tapa-de-vidrio_124046d28dc083810562a2.webp",
    category: "cocina",
    sub_category: "ollas",
  },
  {
    product: "caldero antiadherente experta 20cm universal + tapa de vidrio",
    disponibilidad: true,
    descuento: false,
    id: 112,
    price: "59,000",
    description: "",
    images_url:
      "https://almacencoogranada.com/wp-content/uploads/2020/06/L16400caldero1.jpg",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "caldero fundido 24cm + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: 113,
    price: "59,000",
    description: "",
    images_url:
      "https://i.linio.com/p/dddd647bcef8b1b0d8544ea7863ad546-product.jpg",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product:
      "caldero fundido antiadherente 22cm + tapa de pomo verde universal",
    disponibilidad: true,
    descuento: false,
    id: 114,
    price: "58,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/15/Captura-7.jpeg",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product:
      "sartén talent master deluxe antiadherente 18cm + tapa de vidrio imusa",
    disponibilidad: true,
    descuento: false,
    id: 115,
    price: "58,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/5861032067-2-1fb231dbbb2ee0c2e.webp",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "sartén antiadherente aliada 24cm + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: 116,
    price: "57,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/158113-1200-auto32e145f20004170f.png",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "olla aliada antiadherente 20cm + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: 117,
    price: "55,000",
    description: "",
    images_url:
      "https://almacencoogranada.com/wp-content/uploads/2020/06/L72408ollacocina1.jpg",
    category: "cocina",
    sub_category: "ollas",
  },
  {
    product: "sartén artik 18cm universal",
    disponibilidad: true,
    descuento: false,
    id: 118,
    price: "52,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/Sarten-Artik-Tv-20cm-UNIVERSAL-L37306-3027049_aaed4f3827e7f64ac.webp",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "caldero 20cm con tapa imusa",
    disponibilidad: true,
    descuento: false,
    id: 119,
    price: "51,900",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/159929-800-autoc32852ace8abf460.webp",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "set x2 sartenes aliada 20cm 24cm universal",
    disponibilidad: true,
    descuento: false,
    id: 120,
    price: "50,000",
    description: "",
    images_url:
      "https://hogaruniversal.vtexassets.com/arquivos/ids/158493-1200-auto?v=636816144265300000&width=1200&height=auto&aspect=true",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "caldero fundido 20cm + tapa de pomo verde universal",
    disponibilidad: true,
    descuento: false,
    id: 121,
    price: "49,000",
    description: "",
    images_url:
      "https://www.distribucionescaldas.com/wp-content/uploads/2020/08/SARTEN-6-ULTRATAPA-VIDRIO-18CM-UNIVERSAL_01-300x300.jpg",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "perol artik 18cm + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: 122,
    price: "49,000",
    description: "",
    images_url:
      "https://exitocol.vtexassets.com/arquivos/ids/19049470/Perol-Lpc-Artik-Tv-18cm-UNIVERSAL-L37304-3027051_a.jpg?v=638241826993100000",
    category: "cocina",
    sub_category: "",
  },
  {
    product: "sarten 6 ultra 20cm + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: 123,
    price: "49,000",
    description: "",
    images_url:
      "https://tinypic.host/image/SARTEN-6-ULTRATAPA-VIDRIO-18CM-UNIVERSAL-01-300x300.we5mf",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "caldero fundido 20cm 1libra +  tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: 124,
    price: "46,350",
    description: "",
    images_url:
      "https://homecenterco.scene7.com/is/image/SodimacCO/582243_01?wid=800&hei=800&qlt=70",
    category: "cocina",
    sub_category: "calderos",
  },
  {
    product: "sartén opalo 24cm antiadherente universal",
    disponibilidad: true,
    descuento: false,
    id: 125,
    price: "46,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/Sarten-Opalo-20cm-Sin-Tapa-UNIVERSAL-L37246-3370884_a.png",
    category: "cocina",
    sub_category: "sartenes",
  },
  {
    product: "olla aliada 18cm antiadherente + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: 126,
    price: "45,000",
    description: "",
    images_url:
      "https://fantasygroup.vteximg.com.br/arquivos/ids/180021-1000-1000/image-f15ec5b8947743999d5285c58145944f.jpg?v=637801151533500000",
    category: "cocina",
    sub_category: "ollas",
  },
  {
    product: "perol 6 ultra 16cm + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: 127,
    price: "45,000",
    description: "",
    images_url:
      "https://fantasygroup.vteximg.com.br/arquivos/ids/179901-1000-1000/image-71a30ad437b349c4b56bd2093563fe8f.jpg?v=637801149678100000",
    category: "cocina",
    sub_category: "",
  },
  {
    product: "caldero fundido antiadherente 18cm + tapa de vidrio universal",
    disponibilidad: true,
    descuento: false,
    id: 128,
    price: "44,500",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/15/Caldero-Universal-18Cm-Tv-P-Neg-L7889296e5f5443e008a5a.png",
    category: "cocina",
    sub_category: "calderos",
  },
];
