export const database = [
  {
    product: 'ventilador ciclón 18" universal',
    disponibilidad: true,
    descuento: false,
    id: "001",
    price: "491,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/L75920---VENTILADOR-INDUSTRIAL-CICLON.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador fresh ultra 3 en 1 18" universal',
    disponibilidad: true,
    descuento: false,
    id: "002",
    price: "399,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/119695878_1.jpeg",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador fresh ultra 3 en 1 18" universal',
    disponibilidad: true,
    descuento: false,
    id: "003",
    price: "359,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/6f91be304897dfdef36fed4568858cb3-product.jpeg",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador silence force plus 18" blanco samurai',
    disponibilidad: true,
    descuento: false,
    id: "004",
    price: "289,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/5861030024-1.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: "ventilador fresh de pared universal",
    disponibilidad: true,
    descuento: false,
    id: "005",
    price: "283,900",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/164927-1200-auto.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador 3 en 1 18" blanco kalley',
    disponibilidad: true,
    descuento: false,
    id: "006",
    price: "270,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/157282-1200-auto.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador silence force 18" samurai',
    disponibilidad: true,
    descuento: false,
    id: "007",
    price: "252,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/158282-800-auto.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador ultra power 18" universal',
    disponibilidad: true,
    descuento: false,
    id: "008",
    price: "249,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/D_NQ_NP_683567-MCO32904979542_112019-O.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador 2 en 1 16" negro corona',
    disponibilidad: true,
    descuento: false,
    id: "009",
    price: "210,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/D_NQ_NP_684183-MCO48896089889_012022-O.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'ventilador de piso y pared 8" universal',
    disponibilidad: true,
    descuento: false,
    id: "010",
    price: "129,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/12/159345-1200-auto.png",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: "mini ventilador de mesa y pinza  110v giratorio",
    disponibilidad: true,
    descuento: false,
    id: "011",
    price: "80,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/D_NQ_NP_881680-MCO50529069335_062022-O.webp",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: "ventilador portatil plegable con lampara 20cmx33cm",
    disponibilidad: true,
    descuento: false,
    id: "012",
    price: "75,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/12/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector-1.jpeg",
    category: "electrodomesticos",
    sub_category: "ventiladores",
  },
  {
    product: 'soporte para tv de 40" a 80',
    disponibilidad: true,
    descuento: false,
    id: "013",
    price: "173,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/D_NQ_NP_641713-MCO70610746472_072023-O.webp",
    category: "electrodomesticos",
    sub_category: "televisores",
  },
  {
    product: 'soporte para tv de 14" a 55',
    disponibilidad: true,
    descuento: false,
    id: "014",
    price: "50,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/gsc_126422648_4549529_1.jpeg",
    category: "electrodomesticos",
    sub_category: "televisores",
  },
  {
    product: 'soporte para tv de 14" a 42',
    disponibilidad: true,
    descuento: false,
    id: "015",
    price: "28,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/D_NQ_NP_976169-MLA48232092452_112021-O.webp",
    category: "electrodomesticos",
    sub_category: "televisores",
  },
  {
    product: "cable hdtv 3m",
    disponibilidad: true,
    descuento: false,
    id: "016",
    price: "12,900",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/13/Cable-Hdmi.jpeg",
    category: "electrodomesticos",
    sub_category: "televisores",
  },
  {
    product: "sanduchera 3 en 1 4 puestos universal",
    disponibilidad: true,
    descuento: false,
    id: "017",
    price: "256,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/f3510f82389bf15ad950eb6596039a78-product.jpeg",
    category: "electrodomesticos",
    sub_category: "sanducheras y wafleras",
  },
  {
    product: "sanduchera panini grill universal",
    disponibilidad: true,
    descuento: false,
    id: "018",
    price: "239,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/panini-grill-universal-l87312-negro.webp",
    category: "electrodomesticos",
    sub_category: "sanducheras y wafleras",
  },
  {
    product: "sanduchera 3 en 1 2 puestos universal",
    disponibilidad: true,
    descuento: false,
    id: "019",
    price: "189,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/Sanduchera-UNIVERSAL-Multifuncional---3en1.webp",
    category: "electrodomesticos",
    sub_category: "sanducheras y wafleras",
  },
  {
    product: "sanduchera panini kalley",
    disponibilidad: true,
    descuento: false,
    id: "020",
    price: "119,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/D_NQ_NP_739000-MCO42720126903_072020-O.webp",
    category: "electrodomesticos",
    sub_category: "sanducheras y wafleras",
  },
  {
    product: "sanduchera mini panini universal",
    disponibilidad: true,
    descuento: false,
    id: "021",
    price: "136,200",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/13/162187-1200-auto.webp",
    category: "electrodomesticos",
    sub_category: "sanducheras y wafleras",
  },
  {
    product: "maquina cortadora evok",
    disponibilidad: true,
    descuento: false,
    id: "022",
    price: "168,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/0072216_029e936f3f0064d7375bf20d367b113d9c7bfebf6180d83f02058f58d3ca82ed_450.png",
    category: "salud",
    sub_category: "",
  },
  {
    product: "cojín coxis ortopédico para silla 42cm x 38cm x 12cm",
    disponibilidad: true,
    descuento: false,
    id: "023",
    price: "125,000",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/13/1092_4.webp",
    category: "salud",
    sub_category: "",
  },
  {
    product: "tensiómetro digital jziki",
    disponibilidad: true,
    descuento: false,
    id: "024",
    price: "98,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/D_NQ_NP_814508-MLA54904597227_042023-O.webp",
    category: "salud",
    sub_category: "",
  },
  {
    product: "bascula inteligente peso corporal recargable 25cm x 26cm",
    disponibilidad: true,
    descuento: false,
    id: "025",
    price: "69,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/D_Q_NP_957322-MLA54249617532_032023-O.webp",
    category: "salud",
    sub_category: "",
  },
  {
    product: "dispensador crema dental soporte esterilizador",
    disponibilidad: true,
    descuento: false,
    id: "026",
    price: "46,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/soporte-esterilizador-uv-cepillo-de-dientes-dispensador-crema-dental.webp",
    category: "salud",
    sub_category: "",
  },
  {
    product: "rueda de ejercicios abdominales con tapete",
    disponibilidad: true,
    descuento: false,
    id: "027",
    price: "45,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/Kit-de-rodillos-de-rueda-Abdominal-5-en-1-con-barra-de-realce-cuerda-de-saltar.jpg_.webp",
    category: "salud",
    sub_category: "",
  },
  {
    product: "bascula personal max 150kg",
    disponibilidad: true,
    descuento: false,
    id: "028",
    price: "43,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/bascula-balanza-pesa-personal-bano-vidrio-digital-180k-D_NQ_NP_696087-MCO43675982688_102020-F.jpeg",
    category: "salud",
    sub_category: "",
  },
  {
    product: "set x2 pesas de 2 kilos",
    disponibilidad: true,
    descuento: false,
    id: "029",
    price: "35,500",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/61hBPTY5gYL._AC_SY450_.jpeg",
    category: "salud",
    sub_category: "",
  },
  {
    product: "faja cinturilla reductora neopropeno",
    disponibilidad: true,
    descuento: false,
    id: "030",
    price: "27,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/imageff2192125f8b0cbf.png",
    category: "salud",
    sub_category: "",
  },
  {
    product: "pesa 1kg fisioterapia",
    disponibilidad: true,
    descuento: false,
    id: "031",
    price: "25,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/pesas-fit-dama-hombre-ejercicio-fisioterapia-1-kilo-x1-unidad-kidshoptiendavirtual-1169855311.webp",
    category: "salud",
    sub_category: "",
  },
  {
    product: "taloneras ortopedicas ultra descanso",
    disponibilidad: true,
    descuento: false,
    id: "032",
    price: "21,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/gsc_119215925_2261901_3.jpeg",
    category: "salud",
    sub_category: "",
  },
  {
    product: "corrector de postura lumbar espaldar silla",
    disponibilidad: true,
    descuento: false,
    id: "033",
    price: "20,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/D_NQ_NP_946161-MCO49697721608_042022-O.webp",
    category: "salud",
    sub_category: "",
  },
  {
    product: "pesa fit boy toys 1kg colores varios",
    disponibilidad: true,
    descuento: false,
    id: "034",
    price: "19,900",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/gsc_117936392_1915716_1.jpeg",
    category: "salud",
    sub_category: "",
  },
  {
    product: "mancuerna rusa 2.5kg boy toys",
    disponibilidad: true,
    descuento: false,
    id: "035",
    price: "19,600",
    description: "",
    images_url: "https://tinypic.host/images/2024/01/13/image2.png",
    category: "salud",
    sub_category: "",
  },
  {
    product: "set guante protector de muñeca y tobillo en tela",
    disponibilidad: true,
    descuento: false,
    id: "036",
    price: "15,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/ultunidades-bandas-ortopedicas-modelos-varios.jpeg",
    category: "salud",
    sub_category: "",
  },
  {
    product: "bolsa térmica para agua fría o caliente motivos varios",
    disponibilidad: true,
    descuento: false,
    id: "037",
    price: "14,000",
    description: "",
    images_url:
      "https://tinypic.host/images/2024/01/13/61FunA4l95L._AC_SX425_.jpeg",
    category: "salud",
    sub_category: "",
  },
];
